name: Build cadmium images
on: [push, workflow_dispatch]
jobs:
  build-debian-arm-32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up environment
        run: |
          cd $GITHUB_WORKSPACE
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt update
          sudo apt install -y libunwind-dev
          sudo apt build-dep linux
          sudo apt install gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4   
          
      - name: remove existing config
        run: |
          rm config
          
      - name: build arm32-debian
        run: |
          ls
          cp cadmium-configs/config-arm32-debian config
          sudo ./build-all arm32-debian.img 2G
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: arm32-debian
          path: arm32-debian.img
